insert into teams
    (name)
values
    ('Arizona Cardinals'),
    ('Atlanta Falcons'),
    ('Baltimore Ravens'),
    ('Buffalo Bills'),
    ('Carolina Panthers'),
    ('Chicago Bears'),
    ('Cincinnati Bengals'),
    ('Cleveland Browns'),
    ('Dallas Cowboys'),
    ('Denver Broncos'),
    ('Detroit Lions'),
    ('Green Bay Packers'),
    ('Houston Texans'),
    ('Indianapolis Colts'),
    ('Jacksonville Jaguars'),
    ('Kansas City Chiefs'),
    ('Miami Dolphins'),
    ('Minnesota Vikings'),
    ('New England Patriots'),
    ('New Orleans Saints'),
    ('New York Giants'),
    ('New York Jets'),
    ('Oakland Raiders'),
    ('Philadelphia Eagles'),
    ('Pittsburgh Steelers'),
    ('Los Angeles Rams'),
    ('Los Angeles Chargers'),
    ('San Francisco 49ers'),
    ('Seattle Seahawks'),
    ('Tampa Bay Buccaneers'),
    ('Tennessee Titans'),
    ('Washington Redskins');

    insert into players
        (name, position)
    values
        ('Mitchell Trubisky', 'quarterback'),
        ('Russel Wilson', 'quarterback'),
        ('Melvin Gordon', 'runningback'),
        ('Christian McCaffrey', 'runningback'),
        ('Dalvin Cook', 'runningback'),
        ('Phillip Lindsay', 'runningback'),
        ('Josh Gordon', 'reciever'),
        ('Robert Woods', 'reciever'),
        ('Evan Engram', 'tightend'),
        ('T.Y. Hilton', 'reciever'),
        ('Dede Westbrook', 'reciever'),
        ('Chris Herndon', 'tightend'),
        ('Cordarrelle Patterson', 'reciever/ runningback'),
        ('Eagles D/ST', 'defense'),
        ('Panthers D/ST', 'defense'),
        ('Robbie Gould', 'kicker');